language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements-ci.txt

script:
  - flake8 --exclude=examples/
  - python setup.py develop
  - pytest
  - pytest --cov=aiotask_context tests/
